# Numpy Introduction

In [100]:
import numpy as np

In [101]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [102]:
a2 = a[np.newaxis, :]
print(a2)

[[0 1 2 3 4 5]]


In [103]:
a2.shape

(1, 6)

In [104]:
a.shape 


(6,)

In [105]:
a2 = a[np.newaxis, :]
print(a2)
a2.shape

[[0 1 2 3 4 5]]


(1, 6)

In [106]:
a3 = a2[np.newaxis, :]
print(a3)
a3.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

## Creating Arrays with Numpy

In [107]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.array([(1, 2, 3, 4, 5, 6, 7),(4, 5, 6, 7, 8, 9, 10)])

In [108]:
print(a)
a.shape


[1 2 3 4 5 6 7]


(7,)

In [109]:
print(b)
b.shape

[[ 1  2  3  4  5  6  7]
 [ 4  5  6  7  8  9 10]]


(2, 7)

## initialize arrays

In [110]:
zeros = np.zeros((3,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [111]:
ones = np.ones((2,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [112]:
full = np.full((2,4),5)
full

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [113]:
identity = np.eye(5) # creating an identity matrix
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [114]:
identity.dtype

dtype('float64')

## array attributes

In [115]:
a.shape

(7,)

In [ ]:
len(a) # give us the length of array

7

In [120]:
a.size # give us the numbers of elements in array

7

In [118]:
identity.ndim # give us the dimension of array

2

In [119]:
b.ndim # give us the  dimension of array

2

## basic operations

In [123]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [124]:
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8,  9, 10]])

In [125]:
g = a - b # subtraction
g

array([[ 0,  0,  0,  0,  0,  0,  0],
       [-3, -3, -3, -3, -3, -3, -3]])

In [127]:
h = a + b # addition
h

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [130]:
h1 = np.add(a,b) # another method
h1

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [131]:
# multiplication
i = a * b
i

array([[ 1,  4,  9, 16, 25, 36, 49],
       [ 4, 10, 18, 28, 40, 54, 70]])

In [132]:
# division
d = a / b
d

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
        0.66666667, 0.7       ]])

In [133]:
# square of each element
k = a ** 2
k

array([ 1,  4,  9, 16, 25, 36, 49])

In [99]:
full = np.full((2,5),5)
full

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])