# Numpy (Part-2)

In [2]:
import numpy as np

In [3]:
empty = np.empty((3,4))
print(empty)
print("---------------")
print(empty[1])

[[1.30642903e-311 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [1.33511969e-306 1.04082753e-047 5.33239281e-091 7.24744861e+169]
 [1.28326961e+160 9.59050727e-043 3.99910963e+252 4.93432906e+257]]
---------------
[1.33511969e-306 1.04082753e-047 5.33239281e-091 7.24744861e+169]


In [4]:
x = np.arange(6)
print(x)

[0 1 2 3 4 5]


In [5]:
# array of even numbers from 0 to 23
even = np.arange(0,23,2)
print(even)

[ 0  2  4  6  8 10 12 14 16 18 20 22]


In [6]:
# array of odd numbers from 0 to 23
odd = np.arange(1,23,2)
print(odd)

[ 1  3  5  7  9 11 13 15 17 19 21]


In [7]:
# specific difference between numbers
diff = np.arange(0,23,0.515) # 0.525 is the difference between numbers
print(diff)

[ 0.     0.515  1.03   1.545  2.06   2.575  3.09   3.605  4.12   4.635
  5.15   5.665  6.18   6.695  7.21   7.725  8.24   8.755  9.27   9.785
 10.3   10.815 11.33  11.845 12.36  12.875 13.39  13.905 14.42  14.935
 15.45  15.965 16.48  16.995 17.51  18.025 18.54  19.055 19.57  20.085
 20.6   21.115 21.63  22.145 22.66 ]


In [8]:
lin = np.linspace(0,10,10)
print(lin)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [9]:
lin.dtype

dtype('float64')

In [10]:
# define the data types of array
x = np.arange(0,22.6,1.5, dtype=np.int64)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [11]:
# sorting the array
arr = np.array([2,1,5,3,7,4,6,8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [12]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
# concatenate the arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Concatenate 2D Arrays

In [14]:
x = np.array([[1,2],[3,4]]) # 2x2 array
y = np.array([[5,6]]) # 1x2 array

In [15]:
# concatenate 2D arrays
z = np.concatenate((x,y))
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
len(x)

2

In [17]:
len(y)

1

In [18]:
w = np.array([[5,1], [7,1]]) # 2x2 array

In [19]:
z1 = np.concatenate((w, x), axis=1)
z1

array([[5, 1, 1, 2],
       [7, 1, 3, 4]])

In [20]:
z1.ndim

2

In [21]:
# create a 3D array 
array_example = np.array(
    [[[0, 1, 2, 3],
      [4, 5, 6, 7]]]
)
array_example.ndim

3

In [22]:
# create a consistent 3D array (shape: 3 x 2 x 4)
array_example = np.array([
    [[0, 1, 2, 3],
     [4, 5, 6, 7]],

    [[0, 1, 2, 3],
     [4, 5, 6, 7]],

    [[0, 1, 2, 3],
     [4, 5, 6, 7]]
])
array_example.ndim

3

In [28]:
# create a 3D array of size (3, 1, 4)
a1 = np.array([[[0, 1, 2, 3]],
              [[4, 5, 6, 7]],
              [[0, 1, 2, 3]]])
a1.shape

(3, 1, 4)

In [30]:
a1

array([[[0, 1, 2, 3]],

       [[4, 5, 6, 7]],

       [[0, 1, 2, 3]]])

In [29]:
# rehape the a2
a2 = a.reshape(6, 2)
a2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [0, 1],
       [2, 3]])

In [33]:
a2.reshape(3,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

In [40]:
# create a 1D array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a.shape

(8,)

In [45]:
# convert that into 2D array
b = a[np.newaxis, :]
b.shape

(1, 8)

In [47]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [49]:
c = a[: , np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

# Indexing and Slicing

In [50]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
print(a[-4:-2])

[5 6]


In [60]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
b[0]

array([1, 2, 3, 4])

In [69]:
b[b < 10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
# filter odd numbers
b[b % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [74]:
# use two conditions
b[(b > 2) & (b < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
b[b < 7]

array([1, 2, 3, 4, 5, 6])

In [78]:
# use three conditions and filter the arrays
b[(b > 2) & (b < 11) & (b % 2 == 0)]

array([ 4,  6,  8, 10])

In [79]:
b[(b > 2) | (b < 11)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
lin.dtype

dtype('float64')

In [25]:
random = np.random.random((2,3))
print(random)

[[0.55223675 0.50602132 0.52963716]
 [0.66118332 0.72105531 0.80324546]]
