# Numpy Indexing and Slicing

In [138]:
import numpy as np

In [139]:
# creat an arrray
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [140]:
a[0]

np.int64(1)

In [141]:
b = np.arange(0,12,2)
b

array([ 0,  2,  4,  6,  8, 10])

In [142]:
b[2]

np.int64(4)

In [143]:
c = b.reshape(3,2)
c

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [144]:
c[c > 5]

array([ 6,  8, 10])

In [145]:
c[(c > 2) & (c<8)]

array([4, 6])

## Enlist boolean operators conditional operators?

---
# Making an array from a data or another array

In [146]:
a = np.arange(0,222,5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [147]:
len(a)

45

In [148]:
array1 = a[40:45]
array1

array([200, 205, 210, 215, 220])

In [149]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([8,9,10,11,12,13,14])

In [150]:
c = np.vstack((a,b))
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [151]:
d = np.hstack((a,b))
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [152]:
d = d.reshape(2,7)
d

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

---
# Matrix or Matrices

In [153]:
# create a 2x3 matrix
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [154]:
# create a matrix
b = np.arange(0, 100, 2).reshape(5,10) # array[row_start : row_end , column_start : column_end]
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [155]:
# slicing a matrix
b[0:3, 3:5]

array([[ 6,  8],
       [26, 28],
       [46, 48]])

In [156]:
b.min()

np.int64(0)

In [157]:
b.max()

np.int64(98)

In [158]:
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [159]:
b.max(axis=0) # only for columns

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [160]:
b.max(axis=1) # only for rows

array([18, 38, 58, 78, 98])

In [161]:
m = np.arange(0,20,2).reshape(5,2)
m

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [164]:
np.array([20, 22]) # for visible purpose only

array([20, 22])

In [170]:
m + np.array([20, 22])

array([[20, 24],
       [24, 28],
       [28, 32],
       [32, 36],
       [36, 40]])

In [167]:
np.vstack((m, np.array([42,44])))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [42, 44]])

In [171]:
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [173]:
np.flip(b)

array([[98, 96, 94, 92, 90, 88, 86, 84, 82, 80],
       [78, 76, 74, 72, 70, 68, 66, 64, 62, 60],
       [58, 56, 54, 52, 50, 48, 46, 44, 42, 40],
       [38, 36, 34, 32, 30, 28, 26, 24, 22, 20],
       [18, 16, 14, 12, 10,  8,  6,  4,  2,  0]])

In [122]:
b.max()

np.int64(98)

In [123]:
b.sum()

np.int64(2450)

In [110]:
b[1]

array([10, 12, 14, 16, 18])