In [59]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([69, 27, 58, 57, 76, 89, 72, 17, 23, 95, 11, 22, 18, 84,  3],
      dtype=int32)

In [60]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[76, 26,  5, 65],
       [87, 83, 28, 25],
       [38, 35, 13, 57],
       [29, 89, 56, 96],
       [28,  5, 16, 20],
       [65, 54, 23, 10]], dtype=int32)

In [61]:
# sort
np.sort(a)

array([ 3, 11, 17, 18, 22, 23, 27, 57, 58, 69, 72, 76, 84, 89, 95],
      dtype=int32)

In [62]:
np.sort(b,axis=0)

array([[28,  5,  5, 10],
       [29, 26, 13, 20],
       [38, 35, 16, 25],
       [65, 54, 23, 57],
       [76, 83, 28, 65],
       [87, 89, 56, 96]], dtype=int32)

In [63]:
a

array([69, 27, 58, 57, 76, 89, 72, 17, 23, 95, 11, 22, 18, 84,  3],
      dtype=int32)

In [64]:
# append
np.append(a,200)

array([ 69,  27,  58,  57,  76,  89,  72,  17,  23,  95,  11,  22,  18,
        84,   3, 200])

In [65]:
b

array([[76, 26,  5, 65],
       [87, 83, 28, 25],
       [38, 35, 13, 57],
       [29, 89, 56, 96],
       [28,  5, 16, 20],
       [65, 54, 23, 10]], dtype=int32)

In [66]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[76., 26.,  5., 65.,  1.],
       [87., 83., 28., 25.,  1.],
       [38., 35., 13., 57.,  1.],
       [29., 89., 56., 96.,  1.],
       [28.,  5., 16., 20.,  1.],
       [65., 54., 23., 10.,  1.]])

In [67]:

c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [68]:
# concatenate
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [69]:

np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [70]:
e = np.array([1,1,1,2,3,4,4,4,4,4,4,5,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

`np.expand_dims`
* with the help of numpy.expand_dims() method, we can get the expanded dimensions of an array. 

In [71]:
a

array([69, 27, 58, 57, 76, 89, 72, 17, 23, 95, 11, 22, 18, 84,  3],
      dtype=int32)

In [72]:
np.expand_dims(a,axis=0)

array([[69, 27, 58, 57, 76, 89, 72, 17, 23, 95, 11, 22, 18, 84,  3]],
      dtype=int32)

`np.where`
* The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [73]:
a

array([69, 27, 58, 57, 76, 89, 72, 17, 23, 95, 11, 22, 18, 84,  3],
      dtype=int32)

In [74]:
np.where(a>50) # find all indices with value greater than 50

(array([ 0,  2,  3,  4,  5,  6,  9, 13]),)

In [75]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0, 27,  0,  0,  0,  0,  0, 17, 23,  0, 11, 22, 18,  0,  3],
      dtype=int32)

In [76]:
np.where(a%2 == 0,0,a)

array([69, 27,  0, 57,  0, 89,  0, 17, 23, 95, 11,  0,  0,  0,  3],
      dtype=int32)

`np.argmax`
* the numpy function returns indices of the max element of the array in a particular axis.

In [77]:
a

array([69, 27, 58, 57, 76, 89, 72, 17, 23, 95, 11, 22, 18, 84,  3],
      dtype=int32)

In [78]:
np.argmax(a)

np.int64(9)

In [79]:
b

array([[76, 26,  5, 65],
       [87, 83, 28, 25],
       [38, 35, 13, 57],
       [29, 89, 56, 96],
       [28,  5, 16, 20],
       [65, 54, 23, 10]], dtype=int32)

In [80]:
np.argmax(b)

np.int64(15)

In [81]:
np.argmin(a)

np.int64(14)

In [82]:
np.argmin(b)

np.int64(2)

In [83]:
np.cumsum(a)

array([ 69,  96, 154, 211, 287, 376, 448, 465, 488, 583, 594, 616, 634,
       718, 721])

In [84]:
np.cumsum(b)

array([  76,  102,  107,  172,  259,  342,  370,  395,  433,  468,  481,
        538,  567,  656,  712,  808,  836,  841,  857,  877,  942,  996,
       1019, 1029])

In [85]:
np.sum(b)

np.int64(1029)

In [86]:
a

array([69, 27, 58, 57, 76, 89, 72, 17, 23, 95, 11, 22, 18, 84,  3],
      dtype=int32)

In [87]:
np.cumprod(a)

array([                 69,                1863,              108054,
                   6159078,           468089928,         41660003592,
             2999520258624,      50991844396608,    1172812421121984,
        111417180006588480, 1225588980072473280, 8516213487884860544,
       5717890192251076864,  687430232642114560, 2062290697926343680])

In [88]:
np.cumprod(b)

array([                  76,                 1976,                 9880,
                     642200,             55871400,           4637326200,
               129845133600,        3246128340000,      123352876920000,
           4317350692200000,    56125558998600000,  3199156862920200000,
         541828656138041920, -7117481824842923968,  7249387430406393344,
       -5035081481949200384,  6591671095098802176, -3935132671925092352,
       -7621890529672822784, -4863858003780042752, -2556120992640401408,
       -8903325086614814720, -1862292181335670784,  -176177739647156224])

In [89]:
np.percentile(a,50)

np.float64(57.0)

In [90]:
a

array([69, 27, 58, 57, 76, 89, 72, 17, 23, 95, 11, 22, 18, 84,  3],
      dtype=int32)

In [91]:
np.histogram(a,bins=[0,50,100])

(array([7, 8]), array([  0,  50, 100]))

`np.corrcoef`


In [92]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

`np.isin`

In [93]:
items = [10,20,30,40,50,60,70,80,90,100]
np.isin(a,items)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

`np.flip`

In [94]:
a

array([69, 27, 58, 57, 76, 89, 72, 17, 23, 95, 11, 22, 18, 84,  3],
      dtype=int32)

In [95]:
np.flip(a)

array([ 3, 84, 18, 22, 11, 95, 23, 17, 72, 89, 76, 57, 58, 27, 69],
      dtype=int32)

`np.put`

In [98]:
a

array([100, 110,  58,  57,  76,  89,  72,  17,  23,  95,  11,  22,  18,
        84,   3], dtype=int32)

In [97]:
np.put(a,[0,1],[100,110])
a

array([100, 110,  58,  57,  76,  89,  72,  17,  23,  95,  11,  22,  18,
        84,   3], dtype=int32)

`np.delete`

In [104]:
np.delete(a,[0,1])

array([58, 57, 76, 89, 72, 17, 23, 95, 11, 22, 18, 84,  3], dtype=int32)

`Set Functions`
* np.union1d
* np.intersect1d
* np.setdiff1d
* np.setxor1d

In [106]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [107]:
np.intersect1d(m,n)

array([3, 4, 5])

In [110]:
np.setdiff1d(m,n)

array([1, 2])

In [111]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

`np.clip`

In [115]:
a

array([100, 110,  58,  57,  76,  89,  72,  17,  23,  95,  11,  22,  18,
        84,   3], dtype=int32)

In [116]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 58, 57, 75, 75, 72, 25, 25, 75, 25, 25, 25, 75, 25],
      dtype=int32)